use_frameworks!

platform :ios, '8.0'

target 'FileBrowser_Example' do
  pod 'FileBrowser', :path => '../'

  target 'FileBrowser_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
